import {
  Hungary,
  bg1,
  bg3,
  argentina,
  australia,
  belgium,
  brazil,
  canada,
  china,
  chile,
  czech,
  denmark,
  egypt,
  EU,
  FR,
  GB,
  germany,
  hongkong,
  greece,
  india,
  indonesia,
  Ireland,
  israel,
  italy,
  japan,
  korea,
  malaysia,
  mexico,
  netherlands,
  newzealand,
  Norway,
  philippines,
  Portugal,
  Qatar,
  russia,
  SaudiArabia,
  SouthAfrica,
  Spain,
  SriLanka,
  Switzerland,
  Taiwan,
  Turkey,
  US,
  Venezuela,
} from '../assets';

export const heroData = [
  {
    title: 'Discover Coin Markets',
    description:
      'Explore the markets and trading data for various cryptocurrencies.',
    btn: 'View Coins',
    backgroundImg: bg1,
  },
  {
    title: 'Get the Latest News',
    description:
      'Stay informed with real-time cryptocurrency news and updates.',
    btn: 'Explore News',
    backgroundImg: bg3,
  },
];

export const countries = [
  {
    country: 'Argentina',
    symbol: 'ar',
    entities: 428,
    image: argentina,
  },
  {
    country: 'Australia',
    symbol: 'au',
    entities: 2457,
    image: australia,
  },
  {
    country: 'Belgium',
    symbol: 'be',
    entities: 269,
    image: belgium,
  },
  {
    country: 'Brazil',
    symbol: 'br',
    entities: 2004,
    image: brazil,
  },
  {
    country: 'Canada',
    symbol: 'ca',
    entities: 19662,
    image: canada,
  },
  {
    country: 'Switzerland',
    symbol: 'ch',
    entities: 11796,
    image: Switzerland,
  },
  {
    country: 'Chile',
    symbol: 'cl',
    entities: 6,
    image: chile,
  },
  {
    country: 'China',
    symbol: 'cn',
    entities: 2616,
    image: china,
  },
  {
    country: 'Czech Republic',
    symbol: 'cz',
    entities: 3462,
    image: czech,
  },
  {
    country: 'Germany',
    symbol: 'de',
    entities: 76610,
    image: germany,
  },
  {
    country: 'Denmark',
    symbol: 'dk',
    entities: 804,
    image: denmark,
  },
  {
    country: 'Egypt',
    symbol: 'eg',
    entities: 242,
    image: egypt,
  },
  {
    country: 'Spain',
    symbol: 'es',
    entities: 3849,
    image: Spain,
  },
  {
    country: 'European Union',
    symbol: 'eu',
    entities: 24,
    image: EU,
  },
  {
    country: 'France',
    symbol: 'fr',
    entities: 46465,
    image: FR,
  },
  {
    country: 'United Kingdom',
    symbol: 'gb',
    entities: 19638,
    image: GB,
  },
  {
    country: 'Greece',
    symbol: 'gr',
    entities: 187,
    image: greece,
  },
  {
    country: 'Hong Kong',
    symbol: 'hk',
    entities: 3955,
    image: hongkong,
  },
  {
    country: 'Hungary',
    symbol: 'hu',
    entities: 108,
    image: Hungary,
  },
  {
    country: 'Indonesia',
    symbol: 'id',
    entities: 833,
    image: indonesia,
  },
  {
    country: 'Ireland',
    symbol: 'ie',
    entities: 115,
    image: Ireland,
  },
  {
    country: 'Israel',
    symbol: 'il',
    entities: 1096,
    image: israel,
  },
  {
    country: 'India',
    symbol: 'in',
    entities: 12584,
    image: india,
  },
  {
    country: 'Italy',
    symbol: 'it',
    entities: 5041,
    image: italy,
  },
  {
    country: 'Japan',
    symbol: 'jp',
    entities: 4404,
    image: japan,
  },
  {
    country: 'Korea',
    symbol: 'kr',
    entities: 4820,
    image: korea,
  },
  {
    country: 'Sri Lanka',
    symbol: 'lk',
    entities: 302,
    image: SriLanka,
  },
  {
    country: 'Mexico',
    symbol: 'mx',
    entities: 5433,
    image: mexico,
  },
  {
    country: 'Malaysia',
    symbol: 'my',
    entities: 1023,
    image: malaysia,
  },
  {
    country: 'Netherlands',
    symbol: 'nl',
    entities: 1128,
    image: netherlands,
  },
  {
    country: 'Norway',
    symbol: 'no',
    entities: 937,
    image: Norway,
  },
  {
    country: 'New Zealand',
    symbol: 'nz',
    entities: 421,
    image: newzealand,
  },
  {
    country: 'Philippines',
    symbol: 'ph',
    entities: 5,
    image: philippines,
  },
  {
    country: 'Portugal',
    symbol: 'pt',
    entities: 132,
    image: Portugal,
  },
  {
    country: 'Qatar',
    symbol: 'qa',
    entities: 95,
    image: Qatar,
  },
  {
    country: 'Russian Federation',
    symbol: 'ru',
    entities: 620,
    image: russia,
  },
  {
    country: 'Saudi Arabia',
    symbol: 'sa',
    entities: 248,
    image: SaudiArabia,
  },
  {
    country: 'Turkey',
    symbol: 'tr',
    entities: 607,
    image: Turkey,
  },
  {
    country: 'Taiwan',
    symbol: 'tw',
    entities: 16728,
    image: Taiwan,
  },
  {
    country: 'United States',
    symbol: 'us',
    entities: 39707,
    image: US,
  },
  {
    country: 'Venezuela',
    symbol: 've',
    entities: 111,
    image: Venezuela,
  },
  {
    country: 'South Africa',
    symbol: 'za',
    entities: 752,
    image: SouthAfrica,
  },
];
